name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build Unit Tests
      run: cmake --build build --target unit_tests -j 4

    - name: Run Tests
      working-directory: ./build  # This handles the 'cd build' for you
      run: ctest --output-on-failure